version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket manu-oregon-lambda --no-fail-on-empty-changeset --output-template-file outputTemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
